appName: quantumnest
environment: prod

# Backend configuration
backend:
  replicas: 5
  image:
    repository: registry.example.com/app/backend
    tag: production
    pullPolicy: Always
  containerPort: 3000
  servicePort: 80
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 1Gi
  apiUrl: http://app-backend
  jwtSecret: prod-jwt-secret
  apiKey: prod-api-key

# Frontend configuration
frontend:
  replicas: 5
  image:
    repository: registry.example.com/app/frontend
    tag: production
    pullPolicy: Always
  containerPort: 80
  servicePort: 80
  apiUrl: /api
  service:
    type: ClusterIP
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

# Database configuration
database:
  replicas: 3
  image:
    repository: mysql
    tag: 8.0
    pullPolicy: IfNotPresent
  containerPort: 3306
  servicePort: 3306
  name: quantumnestdb
  user: appuser
  password: prod-password
  rootPassword: prod-root-password
  url: mysql://appuser:prod-password@app-database:3306/appdb
  storageClass: premium-rwo
  storage: 50Gi
  resources:
    limits:
      cpu: 4000m
      memory: 8Gi
    requests:
      cpu: 2000m
      memory: 4Gi

# Redis configuration
redis:
  replicas: 3
  image:
    repository: redis
    tag: 6.2
    pullPolicy: IfNotPresent
  containerPort: 6379
  servicePort: 6379
  storageClass: premium-rwo
  storage: 20Gi
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

# Ingress configuration
ingress:
  host: quantumnest.example.com
  class: nginx
  sslRedirect: "true"
  certManager:
    issuer: letsencrypt-prod

# General configuration
logLevel: warn
imagePullSecrets: regcred
