apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
data:
  API_URL: {{ .Values.backend.apiUrl }}
  REDIS_HOST: {{ .Values.appName }}-redis
  REDIS_PORT: "{{ .Values.redis.containerPort }}"
  DATABASE_HOST: {{ .Values.appName }}-database
  DATABASE_PORT: "{{ .Values.database.containerPort }}"
  DATABASE_NAME: {{ .Values.database.name }}
  DATABASE_USER: {{ .Values.database.user }}
  LOG_LEVEL: {{ .Values.logLevel }}
