apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secrets
type: Opaque
data:
  database-url: {{ .Values.database.url | b64enc }}
  jwt-secret: {{ .Values.backend.jwtSecret | b64enc }}
  mysql-root-password: {{ .Values.database.rootPassword | b64enc }}
  mysql-password: {{ .Values.database.password | b64enc }}
  api-key: {{ .Values.backend.apiKey | b64enc }}
