apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-database
  labels:
    app: {{ .Values.appName }}-database
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.database.servicePort }}
    targetPort: {{ .Values.database.containerPort }}
    protocol: TCP
    name: mysql
  selector:
    app: {{ .Values.appName }}-database
