apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-frontend
  labels:
    app: {{ .Values.appName }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.servicePort }}
    targetPort: {{ .Values.frontend.containerPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.appName }}-frontend
