apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    nginx.ingress.kubernetes.io/ssl-redirect: "{{ .Values.ingress.sslRedirect }}"
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certManager.issuer }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.appName }}-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.appName }}-backend
            port:
              number: {{ .Values.backend.servicePort }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.appName }}-frontend
            port:
              number: {{ .Values.frontend.servicePort }}
