apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-redis
  labels:
    app: {{ .Values.appName }}-redis
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.redis.servicePort }}
    targetPort: {{ .Values.redis.containerPort }}
    protocol: TCP
    name: redis
  selector:
    app: {{ .Values.appName }}-redis
