apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-redis
  labels:
    app: {{ .Values.appName }}-redis
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-redis
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-redis
    spec:
      containers:
      - name: {{ .Values.appName }}-redis
        image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
        imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.redis.containerPort }}
        resources:
          limits:
            cpu: {{ .Values.redis.resources.limits.cpu }}
            memory: {{ .Values.redis.resources.limits.memory }}
          requests:
            cpu: {{ .Values.redis.resources.requests.cpu }}
            memory: {{ .Values.redis.resources.requests.memory }}
        livenessProbe:
          exec:
            command: ["redis-cli", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command: ["redis-cli", "ping"]
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: {{ .Values.appName }}-redis-data
          mountPath: /data
      volumes:
      - name: {{ .Values.appName }}-redis-data
        persistentVolumeClaim:
          claimName: {{ .Values.appName }}-redis-pvc
