apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.appName }}-redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.redis.storageClass }}
  resources:
    requests:
      storage: {{ .Values.redis.storage }}
