---
# roles/database/vars/main.yml
db_name: "{{ db_name }}"
db_user: "{{ db_user }}"
db_password: "{{ db_password }}"
db_root_password: "{{ db_root_password }}"
db_max_connections: 150
db_max_allowed_packet: "64M"
db_innodb_buffer_pool_size: "256M"
db_innodb_log_file_size: "64M"
